BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "LSpaces" (
	"LSpaceID"	INTEGER,
	"LSName"	TEXT NOT NULL UNIQUE,
	"LSSampleSize"	INTEGER NOT NULL,
	"LSDimSize"	INTEGER NOT NULL,
	"LSImageWidth"	INTEGER,
	"LSImageHeight"	INTEGER,
	PRIMARY KEY("LSpaceID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "LSPoints" (
	"LSpaceID"	INTEGER NOT NULL,
	"LSPointID"	INTEGER NOT NULL,
	"LSPointName"	TEXT,
	"LSPointPos"	BLOB NOT NULL,
	"LSPointStd"	BLOB,
	"LSPointImage"	BLOB,
	PRIMARY KEY("LSpaceID","LSPointID"),
	FOREIGN KEY("LSpaceID") REFERENCES "LSpaces"("LSpaceID")
);
CREATE TABLE IF NOT EXISTS "LSClusters" (
	"LSpaceID"	INTEGER NOT NULL,
	"LSClusterName"	TEXT NOT NULL,
	"LSClusterMap"	BLOB NOT NULL,
	"LSClusterLabels"	TEXT,
	PRIMARY KEY("LSpaceID","LSClusterName"),
	FOREIGN KEY("LSpaceID") REFERENCES "LSPoints"("LSpaceID")
);
COMMIT;
